name: Update Tool Links

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  update-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Update links
        run: |
          python .github/scripts/update_links.py
          
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add index.html README.md
          git diff --quiet && git diff --staged --quiet || git commit -m "Update tool links automatically"
          git push 